### ISSUE TITLE
Not updating title on event

### ISSUE THREAD

**Issue by purpletechnician** [temetherian/epitome#8]
I have submitted a A:NR event via NRTM (reg18halmstad).
I forgot to update the title on the event (originally showing Netrunner Tournament #2), but did that afterward. But the title is not updated on the front page.
Can’t access the delete page as I don’t know the password that NRTM creates.

**Comment by temetherian** [comment]
Thanks for the report! Yeah, I think it should be easy enough to parse the title from NRTM's update and update it.

**Comment by purpletechnician** [comment]
Hi again!
Your tool only updates up until last swiss round when I transfer from NRTM.
Is it possible to implement top-cut results also?

Skickat från min iPhone

**Comment by temetherian** [comment]
The top cut should work for letting players see their pairings and match results. (e.g. [http://anr-epitome.appspot.com/reg18halmstad#12](http://anr-epitome.appspot.com/reg18halmstad#12) )

Do you mean something like replacing the standings page with a bracket? That's theoretically doable, but a bit of work.

**Comment by purpletechnician** [comment]
I only see the standing after the 4 swiss rounds, not the final standing after top cut and grand final.
I was hoping of seeing something like the final standing on alwaysberunning.

Yours
Håkan Carlström

Skickat från min iPhone

**Comment by temetherian** [comment]
epiTOME is more focused on providing information to the players during the tournament. (I'll leave final results to ABR.) So if I were to implement top-cut rankings, it would be by presenting a bracket (that gradually gets filled), since that's more useful than standings when the tournament is still happening.

I've made a new issue (#10) for tracking this, though if I'm honest, I'm not really sure when I'll get around to it.
